version: '3.8'
services:
  neo4j:
    image: neo4j
    container_name: neo4j-tutorial
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
